// Auto-generated LP blind-test examples. real:true rounds are unedited live output
// (same base model, once through a captured voice, once with a normal prompt).
export interface QuizExample { label: string; brief: string; human: string; ai: string; real: boolean; }
export const QUIZ_EXAMPLES: QuizExample[] = [
  {
    "label": "A landing-page headline for a scheduling tool",
    "brief": "",
    "human": "Stop emailing back and forth about times. Send one link. Done.",
    "ai": "Revolutionize Your Productivity With Our Cutting-Edge, AI-Powered Scheduling Solution",
    "real": false
  },
  {
    "label": "A founder’s weekly newsletter post",
    "brief": "Idea: founders obsess over competitors’ feature launches, but churned-customer exit interviews show the real competitor is almost always the status quo — a spreadsheet, an intern, or nothing at all. The competitor slide is a vanity document.",
    "human": "I asked a founder last week to send me their last five churned-customer exit interviews.\n\nBefore I opened them, I asked him: “Who do you think you lost these deals to?”\n\nHe named two competitors. Real companies, funded, logos I recognized. He’d built a whole competitive matrix around them - feature checkboxes, pricing comparisons, a battle card his sales team was supposed to memorize.\n\nI opened the exit interviews. Here’s who he actually lost to:\n-\n\n“We just kept using the spreadsheet, honestly.”\n-\n\n“Our ops person handles it manually, it’s fine.”\n-\n\n“We never really got around to fully switching over, so we just… didn’t.”\n-\n\n“Our intern does this once a week, takes her like an hour.”\n-\n\n“Nothing changed, we just stopped prioritizing it.”\n\nZero out of five lost to a competitor. Five out of five lost to the status quo.\n\nThis is almost always true, and almost nobody believes it about their own business - myself included. I’ve built this exact battlecard before, more than once. At my last startup, I could tell you our competitor’s pricing, their last three feature launches, and the name of their VP of Sales. I could not have told you, without being forced to go dig through exit interviews, that the actual thing beating us was a shared Google Sheet three different customers had independently built to do 80% of what we did, for free, badly, forever.\n\nWhy we obsess over the wrong competitor\n\nCompetitors are legible. They have websites, pricing pages, Twitter accounts, funding announcements. You can screenshot their new feature and slack it to your team with a panicked “did you see this?!” It feels like real, urgent, actionable information.",
    "ai": "Your biggest competitor probably isn't who you think it is.\n\nI see founders spend hours mapping out competitor decks, tracking their pricing changes, obsessing over feature parity.\n\nMeanwhile, the thing actually killing their deals?\n\nThe spreadsheet their prospect has used for 5 years.\nThe manual process nobody loves but everyone tolerates.\nThe \"we've always done it this way\" mentality.\n\nThe status quo doesn't need a marketing budget. It doesn't need a sales team. It just needs inertia—and inertia is a powerful, patient opponent.\n\nHere's what this means in practice:\n\n→ Your pitch shouldn't just be \"better than Competitor X.\" It should answer: \"Why change at all?\"\n\n→ Your real sales cycle isn't fighting for market share—it's fighting apathy, risk-aversion, and \"maybe next quarter.\"\n\n→ The switching cost isn't just money. It's the mental energy of learning something new, the fear of disruption, the political capital of championing change internally.\n\nI've watched startups win against well-funded competitors and lose to nothing—to a prospect simply deciding the current (worse) way was safe enough.\n\nSo before you obsess over the competitive landscape, ask:\n\n- What does life look like for my customer if they do nothing?\n- Am I selling a better solution, or am I selling change itself?\n- Have I made the cost of inaction visceral and clear?\n\nThe startups that win aren't always the ones with the best product. They're the ones who understand that status quo bias is the default setting of human behavior—and they design their entire GTM motion around overcoming it.\n\nStop only watching your competitors. Start studying inertia.\n\nThat's the real fight.\n\n---\n\nWhat's been your experience—have you lost more deals to competitors or to \"no decision\"?",
    "real": true
  },
  {
    "label": "An AI creator’s short-video script",
    "brief": "Idea + research: the AI productivity paradox. METR study — developers FELT 20% faster with AI but were measured 19% SLOWER. Electricity analogy — factories took ~30 years to see gains because they had to redesign the whole workflow, not just swap the power source. End: tell viewers to time one real task with and without AI.",
    "human": "I saw this study from METR this week and I have not stopped thinking about it since. They had experienced developers use AI tools to do real coding tasks. Afterwards, the devs said, yeah, that felt like I was about 20% faster. Cool. Except when they actually measured it, these developers were 19% slower. Not a typo. Slower. They felt fast. They were not fast.\n\nOkay, so here's what I think is actually going on, broken into a few pieces.\n\nOne, the vibe lies. Feeling fast and being fast are two completely different measurements, and most of us are only checking the first one.\n\nTwo, this is not even a new story. It just has an AI costume on. When factories first switched from steam power to electricity, everybody assumed productivity would skyrocket overnight. Flip the switch, boom, efficiency. It took 30 years. Three decades. Because the problem was never the power source, it was the layout. Every machine was arranged around one giant steam engine and a system of shafts and belts. Electricity let you put a small motor on every single machine, but nobody redesigned the floor plan for decades. They just swapped the engine and expected magic.\n\nThree, that's exactly what's happening with AI right now. People are bolting a chatbot onto the exact same workflow they had before and wondering why the whole thing doesn't feel transformed. You didn't redesign anything. You just added a really fast, really confident intern into a process that was never built to use them well.\n\nSo here's what I want you to actually do. Pick one task you do regularly, something you've used AI on and assumed is saving you time, and time yourself doing it with AI and without it. Not a feeling, an actual stopwatch.\n\nTry it this week and let me know in the comments what you find. I have a feeling some of you are going to be surprised.",
    "ai": "VIDEO SCRIPT: \"Why Isn't AI Making Us Faster?\"\n\n[COLD OPEN — Direct to camera, energetic]\n\nOkay, quick question: if AI is supposedly making all of us superhuman... why do companies spend billions on it and see basically nothing show up in the productivity numbers?\n\nThis is called the AI Productivity Paradox, and it's one of the weirdest stories in tech right now. Let's get into it.\n\n[BEAT 1 — The setup]\n\nSo businesses everywhere are pouring money into AI tools. Copilots, chatbots, automated everything. And when you ask people, \"Hey, does this make you faster?\" — they say yes! Absolutely, love it, couldn't work without it.\n\nBut zoom out to the actual company-level data — output, revenue per employee, delivery speed — and the needle barely moves. Sometimes it doesn't move at all.\n\n[BEAT 2 — The killer stat]\n\nHere's the part that should stop you in your tracks. There was a study — the METR study — where they had experienced software developers use AI tools to do real coding tasks.\n\nAfterward, the devs said: \"Yeah, that was about 20% faster.\"\n\nThen researchers checked the actual clock time.\n\nThey were 19% slower.\n\n[Pause. Let that land.]\n\nNot a little slower — slower, while feeling dramatically faster. That gap between perception and reality? That's the whole paradox in one experiment.",
    "real": true
  }
];
